version: '3'
services:
    backend:
        image: node:latest
        working_dir: /backend
        command: /bin/bash -c "npm run docker-watch"
        volumes:
            - ./backend:/backend
            - ./interface:/interface
        ports:
            - 8080:8080
        depends_on:
            - database
    database:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/data/log
        volumes:
            - /data/db
            - /data/log
        ports:
            - 27017:27017
        command: mongod --smallfiles --bind_ip_all # --quiet
