version: '3'
services:
   frontend:
      image: pepeblack/chumm-uffa-frontend:latest
      ports:
         - 80:80
      depends_on:
          - backend
   backend:
      image: pepeblack/chumm-uffa-backend:latest
      depends_on:
          - database
   database:
      image: mongo:latest
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/data/log
      volumes:
          - /data/db
          - /data/log
      command: mongod --smallfiles --bind_ip_all # --quiet